# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seu_servico.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11seu_servico.proto\x12\x0bseu.servico\"2\n\x04\x44\x61\x64o\x12\r\n\x05\x63have\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x65sc\x18\x02 \x01(\t\x12\r\n\x05valor\x18\x03 \x01(\x02\"\x1b\n\tResultado\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32H\n\nSeuServico\x12:\n\x0bInserirDado\x12\x11.seu.servico.Dado\x1a\x16.seu.servico.Resultado\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seu_servico_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DADO._serialized_start=34
  _DADO._serialized_end=84
  _RESULTADO._serialized_start=86
  _RESULTADO._serialized_end=113
  _SEUSERVICO._serialized_start=115
  _SEUSERVICO._serialized_end=187
# @@protoc_insertion_point(module_scope)
